#ifndef UTIL_H
#define UTIL_H

typedef enum {
	SOUND_BACKGROUND,
	SOUND_PLAYER_TALKING,
	SOUND_KALIPSO_TALKING_LOW_SUSPICION,
	SOUND_KALIPSO_TALKING_MEDIUM_SUSPICION,
	SOUND_KALIPSO_TALKING_HIGH_SUSPICION,
	SOUND_PLAYER_WALKING,
	SOUND_TREE_BREAKING,
	SOUND_TREE_BROKEN,
	SOUND_WEED_BREAKING,
	SOUND_WEED_BROKEN,
	SOUND_DEPOSITED_TO_RAFT,
	SOUND_ENUM_COUNT
} SoundType;

typedef enum {
	TEXTURE_BACKGROUND,
	TEXTURE_OCEAN,
	TEXTURE_PLAYER,
	TEXTURE_KALIPSO,
	TEXTURE_TREE,
	TEXTURE_WEED,
	TEXTURE_RAFT,
	TEXTURE_ENUM_COUNT
} TextureType;

#endif // UTIL_H
