#ifndef UTIL_H
#define UTIL_H

typedef enum {
	SOUND_BACKGROUND,
	SOUND_PLAYER_WALKING,
	SOUND_TREE_BREAKING,
	SOUND_TREE_BROKEN,
	SOUND_WEED_BREAKING,
	SOUND_WEED_BROKEN,
	SOUND_DEPOSITED_TO_RAFT,
	SOUND_ENUM_COUNT
} SoundType;

#endif // UTIL_H
